---
  apiVersion: "v1"
  kind: "ReplicationController"
  metadata: 
    name: "jenkins"
    labels: 
      name: "jenkins"
  spec: 
    replicas: 1
    template: 
      metadata: 
        name: "jenkins"
        labels: 
          name: "jenkins"
      spec: 
        containers: 
          - name: "jenkins"
            image: "csanchez/jenkins-kubernetes:latest"
            ports: 
              - containerPort: 8080
              - containerPort: 50000
            volumeMounts: 
              - name: "jenkins-data"
                mountPath: "/var/jenkins_home"
            livenessProbe:
              httpGet:
                path: /
                port: 8080
              initialDelaySeconds: 60
              timeoutSeconds: 5
        volumes: 
          - name: "jenkins-data"
            hostPath:
              path: "/data/jenkins"
